### PR TITLE
Removed private API key and client ID out of source control

### PR DESCRIPTION
**Pull request by jonalmeida**
After committing this change, please revoke your old API key that you've committed into this public github repository and generate a new one that you can put into `ApiKey.java` (after renaming from `ApiKey.java.in`).

### CODE REVIEW

**Comment by DSteve595** [comment]
This definitely seems like a good idea. Thanks for the solution!

**Comment by jonalmeida** [comment]
Great!

**Comment by DSteve595** [comment]
Why `.java.in` instead of just `.java`?

**Comment by jonalmeida** [comment]
`.java.in` is the template file. I've add the `.java` file to the .gitignore so it won't be committed by someone by mistake. The template file forces a new person to see and edit the file first.

**Comment by DSteve595** [comment]
That would make the build fail after checkout, right?

**Comment by jonalmeida** [comment]
Intentionally, yes. I see your point though..

I force commited the ApiKey.java file as the template but that will now fail with the NullPointerException and throw the appropriate error.

**Comment by DSteve595** [comment]
I think I'd rather have it just be `ApiKey.java`, so it builds correctly, and I'll just keep my local copy private (and gitignored) with the new key.

**Comment by jonalmeida** [comment]
I've updated the PR change to make change it into `ApiKey.java`. It'll "sort of" fail the first time only if you try to build right after cloning the repo.

A one-time (intentional) build failure is a lot safer against newbie mistakes :)

**Comment by DSteve595** [comment]
Looks good.

**Pull request merged**
