### PR TITLE
Api README doc updates

### PR DESCRIPTION
**Pull request by jonalmeida**
Depends on #36 and #35 before merging.

### CODE REVIEW

**Comment by DSteve595** [comment]
What does this change? Seems like your other two PRs put together.

**Comment by jonalmeida** [comment]
Whoops, one sec!

**Comment by jonalmeida** [comment]
There we go! Forgot to push my changes :)

**Comment by DSteve595** [comment]
Could you rebase your branch onto the new commit you made for #35? It's trying to merge the old commit (check the diff).

**Comment by jonalmeida** [comment]
Done!

**Comment by DSteve595** [comment]
Some of the whitespace and line endings got messed up so I did some changes and pushed to master. Thanks for the help.

**Comment by jonalmeida** [comment]
Sorry, my editor removes trailing whitespaces.

**Pull request closed without merging**
