### PR TITLE
Android TV Support

### PR DESCRIPTION
**Pull request by sregg**
Hi Steve,

Here is the first version of the Android TV support.
I tried to keep it isolated from your code using a "tv" package name but I had to add some equals and hashCode in `PutioFile.java`.
The imls also got somehow changed by Android Studio.
And I added some leanback stuff in `AndroidManifest.xml` and `build.gradle`.

Right now it lists the folders and video files only. Only MP4 files (original or converted) are supported for now.
We'll see if people ask for MP3 audio support.

Some colouring could be done too.

Here are some screenshots:

Icon in TV Launcher:
tv_screenshot_launcher

Grid of Folders:
tv_screenshot_folders

Grid of Videos:
tv_screenshot_videos

Video Playing:
tv_screenshot_playing

### CODE REVIEW

**Comment by DSteve595** [comment]
This is amazing, thank you so much for the time you've put into this. It looks great! I'll add a credit in About.
Will merge ASAP.

**Comment by DSteve595** [comment]
Merging into `tv` branch.

**Comment by sregg** [comment]
Great.
Make sure to Opt-In to Android TV in the Developer Console:
https://developer.android.com/distribute/googleplay/tv.html

**Comment by f1vefour** [comment]
Nice work.

**Comment by sregg** [comment]
I fixed issues #1 #2 and #3 from Bryan's feedback (https://plus.google.com/105808556258081643168/posts/H7WHpvcXyWL)

**Comment by rgbk** [comment]
Where does one start if the videos aren't playing back. I get all the screens above, I have totally regular videos on my put.io. Clealry since I'm using the app, and an android tv, it can't be anything I'm doing wrong. I'm on a 4K UHD Bravia 2015, good WIFI. Any suggestions welcome and happy to help debug. Thanks.

**Comment by DSteve595** [comment]
I'm not super familiar with the TV functionality (@sregg implemented it) but I'll see if I can find what's wrong when I can.

**Pull request merged**
